### ISSUE TITLE
Implement Fiber::SchedulerInterface

### ISSUE THREAD

**Issue by wjordan** [digital-fabric/polyphony#46]
With the release of Ruby 3.0 and the new [`Fiber::SchedulerInterface`](https://ruby-doc.org/core-3.0.0/Fiber/SchedulerInterface.html) for implementing [non-blocking fibers](https://ruby-doc.org/core-3.0.0/Fiber.html#class-Fiber-label-Non-blocking+Fibers), it seems that a consensus has formed around this new interface for building Fiber-based concurrent applications, and considering the programming model and API this project offers has very similar goals, I think it would be a smart move to pivot in alignment. It would be super useful to Ruby 3.0+ applications (and also extremely helpful for broader adoption of this library) if Polyphony could implement `SchedulerInterface` and allow its high-performance event-reactor implementation to be used via [`Fiber.set_scheduler`](https://ruby-doc.org/core-3.0.0/Fiber.html#method-c-set_scheduler) in any Ruby 3 application (as an alternative to the [`evt`](https://github.com/dsh0416/evt) or [`async`](https://github.com/dsh0416/evt) implementations).

As a further thought, perhaps an interesting pivot for the rest of polyphony's set of stdlib extensions and patches could be to make it function as a Fiber-scheduler 'polyfill', allowing the existing extensions to IO, Kernel etc. to implement (at least parts of) the fiber-scheduler interface on pre-3.0 ruby versions. Having an API-compatible polyfill would allow libraries a smoother transition towards adopting non-blocking fibers without immediately requiring upgrades to Ruby 3.0. This might be trickier to sort out than a `SchedulerInterface` implementation but could have a significant impact if successful.

**Comment by ciconia** [comment]
I have extracted some of the Polyphony code into a separate project that implements the fiber scheduler interface: https://github.com/digital-fabric/libev_scheduler. The README includes my critique of this new Ruby 3.0 feature, and also explains 

Polyphony (re)implements the Ruby I/O API in order to be fully profit from io_uring (not possible using the fiber scheduler interface, since it only deals with I/O readiness and not the actual I/O ops). And then Polyphony goes way beyond mere fiber-aware blocking operations, providing robust exception handling, structured concurrency, and dealing with lots of edge cases encountered when using multiple fibers (for example trapping signals and forking).

For the moment I don't see the advantage in aligning Polyphony with the fiber scheduler interface. In some ways, it would limit what Polyphony can do - for example with Polyphony you can use the main fiber just like any other fiber, with the fiber scheduler interface you can't.

So actually the way I see it, apart from employing Ruby fibers for concurrency, there's very little in common between Polyphony and  the new fiber scheduler interface.

**Comment by wjordan** [comment]
Thanks so much for the pointer to the separate scheduler-implementation project! That looks exactly what I was hoping for, I'll follow up over there as I have time to experiment with it further.
